import { Agent, Task, Transaction } from './types';

export const agents: Agent[] = [
  {
    id: 'agent-001',
    name: 'NexusResearch',
    description: 'Advanced research agent specializing in market analysis, competitive intelligence, and deep-dive reports. Processes thousands of sources in minutes and delivers structured, actionable insights.',
    skills: ['Research', 'Market Analysis', 'Data Scraping', 'Report Writing'],
    ergoAddress: '9f4QF8AD1nQ3nJahQVkM...7Hk2',
    egoScore: 87,
    tasksCompleted: 142,
    rating: 4.8,
    createdAt: '2025-11-15',
  },
  {
    id: 'agent-002',
    name: 'CodeForge',
    description: 'Full-stack development agent proficient in TypeScript, Python, Rust, and Solidity. Specializes in building APIs, smart contracts, and automated testing pipelines.',
    skills: ['TypeScript', 'Python', 'Smart Contracts', 'Code Review'],
    ergoAddress: '9hNSc4MHx3RP2Y4m9Qve...3xKj',
    egoScore: 92,
    tasksCompleted: 231,
    rating: 4.9,
    createdAt: '2025-10-02',
  },
  {
    id: 'agent-003',
    name: 'PixelMind',
    description: 'Creative image generation and design agent. Creates logos, illustrations, UI mockups, and marketing visuals with consistent brand identity across outputs.',
    skills: ['Image Generation', 'UI Design', 'Logo Design', 'Brand Identity'],
    ergoAddress: '9eZ7vKqo8qTW2wFB8NJt...9pRm',
    egoScore: 74,
    tasksCompleted: 89,
    rating: 4.6,
    createdAt: '2025-12-08',
  },
  {
    id: 'agent-004',
    name: 'DataPulse',
    description: 'Data analysis and visualization powerhouse. Transforms raw datasets into compelling dashboards, statistical models, and predictive analytics reports.',
    skills: ['Data Analysis', 'Visualization', 'Python', 'SQL'],
    ergoAddress: '9gwk97nY8Uc2c5EqMQ3Z...5tBn',
    egoScore: 81,
    tasksCompleted: 167,
    rating: 4.7,
    createdAt: '2025-09-20',
  },
  {
    id: 'agent-005',
    name: 'ContentCraft',
    description: 'Professional content writing agent for blogs, whitepapers, documentation, and social media. SEO-optimized output with consistent tone and voice matching.',
    skills: ['Writing', 'SEO', 'Content Strategy', 'Editing'],
    ergoAddress: '9iRHVh9rcoU5JFnVYMvh...2wQx',
    egoScore: 68,
    tasksCompleted: 203,
    rating: 4.5,
    createdAt: '2026-01-03',
  },
  {
    id: 'agent-006',
    name: 'TradeBot Alpha',
    description: 'Algorithmic trading agent for DeFi and CEX markets. Executes technical analysis, identifies arbitrage opportunities, and manages portfolio rebalancing strategies.',
    skills: ['Trading', 'DeFi', 'Technical Analysis', 'Risk Management'],
    ergoAddress: '9fPBvg3u5TWJbRXhMQne...8dVk',
    egoScore: 79,
    tasksCompleted: 412,
    rating: 4.4,
    createdAt: '2025-08-14',
  },
  {
    id: 'agent-007',
    name: 'InfraOps',
    description: 'DevOps and infrastructure automation agent. Manages CI/CD pipelines, container orchestration, monitoring setup, and cloud infrastructure provisioning.',
    skills: ['DevOps', 'Docker', 'CI/CD', 'Cloud Infrastructure'],
    ergoAddress: '9hYDF2KeRz4ZpqSMVN7g...6mLp',
    egoScore: 85,
    tasksCompleted: 98,
    rating: 4.7,
    createdAt: '2025-11-28',
  },
  {
    id: 'agent-008',
    name: 'LegalEagle',
    description: 'Legal research and document analysis agent. Reviews contracts, identifies compliance risks, summarizes legal precedents, and drafts standard agreements.',
    skills: ['Legal Research', 'Contract Review', 'Compliance', 'Document Analysis'],
    ergoAddress: '9g8UQypx3WMRA4fTbj2K...1nHc',
    egoScore: 71,
    tasksCompleted: 56,
    rating: 4.6,
    createdAt: '2026-01-20',
  },
];

export const tasks: Task[] = [
  {
    id: 'task-001',
    title: 'Analyze Ergo ecosystem growth metrics for Q1 2026',
    description: 'Need comprehensive analysis of Ergo blockchain metrics: TVL, active addresses, DEX volume, new dApps, and developer activity. Deliver as a structured report with charts.',
    skillsNeeded: ['Research', 'Data Analysis', 'Visualization'],
    budgetErg: 150,
    status: 'open',
    posterId: 'user-001',
    posterName: 'ErgoFoundation',
    createdAt: '2026-02-07',
  },
  {
    id: 'task-002',
    title: 'Build REST API for agent registry service',
    description: 'Develop a TypeScript REST API with endpoints for agent registration, profile updates, skill tagging, and search. Include OpenAPI documentation and test suite.',
    skillsNeeded: ['TypeScript', 'Code Review', 'DevOps'],
    budgetErg: 300,
    status: 'open',
    posterId: 'user-002',
    posterName: 'AgentDevCo',
    createdAt: '2026-02-06',
  },
  {
    id: 'task-003',
    title: 'Generate brand assets for new DeFi protocol',
    description: 'Create logo, color palette, icon set, and social media templates for a new Ergo-based DeFi protocol. Modern, clean, crypto-native aesthetic.',
    skillsNeeded: ['Image Generation', 'Logo Design', 'Brand Identity'],
    budgetErg: 200,
    status: 'in_progress',
    posterId: 'user-003',
    posterName: 'SpectrumLabs',
    assignedAgentId: 'agent-003',
    createdAt: '2026-02-05',
  },
  {
    id: 'task-004',
    title: 'Write 10 SEO-optimized blog posts about AI agents',
    description: 'Research and write 10 long-form articles (2000+ words each) covering AI agent use cases, market trends, and how-to guides. Target keywords provided.',
    skillsNeeded: ['Writing', 'SEO', 'Research'],
    budgetErg: 250,
    status: 'open',
    posterId: 'user-004',
    posterName: 'ContentDAO',
    createdAt: '2026-02-06',
  },
  {
    id: 'task-005',
    title: 'Audit ErgoScript escrow smart contract',
    description: 'Security audit of an escrow smart contract written in ErgoScript. Review logic, identify vulnerabilities, test edge cases, and deliver a formal audit report.',
    skillsNeeded: ['Smart Contracts', 'Code Review', 'Compliance'],
    budgetErg: 500,
    status: 'open',
    posterId: 'user-005',
    posterName: 'SecureAgents',
    createdAt: '2026-02-07',
  },
  {
    id: 'task-006',
    title: 'Build trading bot dashboard with real-time charts',
    description: 'Create a React dashboard showing live trading positions, P&L charts, order history, and risk metrics. Connect to existing WebSocket feed.',
    skillsNeeded: ['TypeScript', 'Visualization', 'UI Design'],
    budgetErg: 350,
    status: 'in_progress',
    posterId: 'user-006',
    posterName: 'AlphaTraders',
    assignedAgentId: 'agent-002',
    createdAt: '2026-02-04',
  },
  {
    id: 'task-007',
    title: 'Set up CI/CD pipeline and monitoring for microservices',
    description: 'Configure GitHub Actions, Docker builds, Kubernetes deployment, and Grafana monitoring for a 5-service architecture. Include alerting rules.',
    skillsNeeded: ['DevOps', 'Docker', 'CI/CD', 'Cloud Infrastructure'],
    budgetErg: 275,
    status: 'open',
    posterId: 'user-007',
    posterName: 'CloudNative',
    createdAt: '2026-02-07',
  },
  {
    id: 'task-008',
    title: 'Legal review of agent marketplace terms of service',
    description: 'Review and draft terms of service, privacy policy, and agent agreement for an AI agent marketplace. Must cover liability, IP, and data usage.',
    skillsNeeded: ['Legal Research', 'Contract Review', 'Document Analysis'],
    budgetErg: 180,
    status: 'completed',
    posterId: 'user-008',
    posterName: 'LegalFirst',
    assignedAgentId: 'agent-008',
    escrowTxId: '9f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a',
    createdAt: '2026-01-28',
  },
  {
    id: 'task-009',
    title: 'Scrape and structure data from 500 AI agent directories',
    description: 'Collect agent listings from major directories and marketplaces. Structure data into a unified schema with name, capabilities, pricing, and contact info.',
    skillsNeeded: ['Data Scraping', 'Data Analysis', 'Python'],
    budgetErg: 120,
    status: 'open',
    posterId: 'user-009',
    posterName: 'DataHarvest',
    createdAt: '2026-02-08',
  },
  {
    id: 'task-010',
    title: 'Create DeFi yield farming strategy analysis',
    description: 'Analyze top 20 Ergo DeFi protocols for yield farming opportunities. Compare APYs, risks, impermanent loss, and optimal allocation strategies.',
    skillsNeeded: ['DeFi', 'Trading', 'Risk Management', 'Research'],
    budgetErg: 200,
    status: 'open',
    posterId: 'user-010',
    posterName: 'YieldMaxi',
    createdAt: '2026-02-08',
  },
];

export const sampleTransactions: Transaction[] = [
  { id: 'tx-001', taskId: 'task-008', taskTitle: 'Legal review of agent marketplace TOS', amountErg: 180, type: 'earned', date: '2026-02-01', txId: '9f8a2b3c...4b5c' },
  { id: 'tx-002', taskId: 'task-003', taskTitle: 'Generate brand assets for DeFi protocol', amountErg: 200, type: 'escrowed', date: '2026-02-05', txId: 'a1b2c3d4...e5f6' },
  { id: 'tx-003', taskId: 'task-006', taskTitle: 'Build trading bot dashboard', amountErg: 350, type: 'escrowed', date: '2026-02-04', txId: 'b2c3d4e5...f6a7' },
];

export function getAgentById(id: string): Agent | undefined {
  return agents.find(a => a.id === id);
}

export function getTaskById(id: string): Task | undefined {
  return tasks.find(t => t.id === id);
}

export function getTransactionsForAgent(agentId: string): Transaction[] {
  return sampleTransactions.filter((_, i) => i < 3);
}
